POST http://localhost:8384/unregister?service=io.github.hefrankeleyn.hefrpc.UserService
Content-Type: application/json

{
  "schema": "http",
  "host": "localhost",
  "port": 8082,
  "context": "hefrpc",
  "parameters": {
    "grey": false,
    "dc": "bj",
    "union": "B01"
  }
}

### register
POST http://localhost:8383/register?service=io.github.hefrankeleyn.hefrpc.UserService
Content-Type: application/json

{
  "schema": "http",
  "host": "localhost",
  "port": 8082,
  "context": "hefrpc",
  "parameters": {
    "grey": false,
    "dc": "bj",
    "union": "B01"
  }
}

### findAllInstances 8383
GET http://localhost:8383/findAllInstances?service=io.github.hefrankeleyn.hefrpc.UserService
Accept: application/json

### findAllInstances 8384
GET http://localhost:8384/findAllInstances?service=io.github.hefrankeleyn.hefrpc.UserService
Accept: application/json

### findAllInstances 8385
GET http://localhost:8385/findAllInstances?service=io.github.hefrankeleyn.hefrpc.UserService
Accept: application/json

###
GET http://localhost:8383/version?service=io.github.hefrankeleyn.hefrpc.UserService
Accept: application/json


### renew
POST http://localhost:8383/renew?service=io.github.hefrankeleyn.hefrpc.UserService
Content-Type: application/json

{
  "schema": "http",
  "host": "localhost",
  "port": 8085,
  "context": "hefrpc",
  "parameters": {
    "grey": false,
    "dc": "bj",
    "union": "B01"
  }
}

### info
GET http://localhost:8385/info
Accept: application/json

### cluster
GET http://localhost:8384/cluster
Accept: application/json

### cluster
GET http://localhost:8385/leader
Accept: application/json


### sf
GET http://localhost:8385/sf
Accept: application/json

### snapshot
GET http://localhost:8383/snapshot
Accept: application/json